# Generated by Django 5.2.4 on 2026-07-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('1h', '1 Hour'), ('4h', '4 Hour'), ('1d', '1 Day'), ('general', 'General')], default='1h', max_length=10)),
                ('raw_inputs', models.JSONField(default=dict)),
                ('model_prediction', models.CharField(blank=True, max_length=30)),
                ('model_confidence', models.FloatField(default=0.0)),
                ('actual_outcome', models.CharField(blank=True, choices=[('', 'Not set yet'), ('Bullish', 'Bullish ▲ (NQ closed above open)'), ('Neutral', 'Neutral ↔ (NQ stayed flat)'), ('Bearish', 'Bearish ▼ (NQ closed below open)')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trading Day',
                'verbose_name_plural': 'Trading Days',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
